# Generated by Django 4.2.3 on 2023-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Article_name", models.CharField(max_length=100)),
                ("Article_number", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "app1",
            },
        ),
    ]
